/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/layout/Aside.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    CounterInput: typeof import('./src/components/CounterInput.vue')['default']
    CustomButton: typeof import('./src/components/CustomButton.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    DateFormatter: typeof import('./src/components/DateFormatter.vue')['default']
    Drawer: typeof import('primevue/drawer')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    EmailInput: typeof import('./src/components/EmailInput.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IftaLabel: typeof import('primevue/iftalabel')['default']
    Image: typeof import('primevue/image')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    NumberInput: typeof import('./src/components/NumberInput.vue')['default']
    OrderStatus: typeof import('./src/components/OrderStatus.vue')['default']
    Password: typeof import('primevue/password')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectInput: typeof import('./src/components/SelectInput.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TextInput: typeof import('./src/components/TextInput.vue')['default']
    TextLink: typeof import('./src/components/TextLink.vue')['default']
    WrapperDashboard: typeof import('./src/components/layout/WrapperDashboard.vue')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
